// examples/showcase/src/preact-ticker.preact.tsx
/** @jsxImportSource preact */
import { useEffect, useState } from "preact/hooks";

import { deckPreact } from "@kadal/deck-preact";

/**
 * A Preact component on a slide, for the islands tour.
 *
 * `.preact.tsx` keeps React's Vite plugin off it; unlike Solid there is no second plugin to add,
 * because the pragma above is the whole configuration. The JSX transform already supports a
 * per-file import source, so this file compiles to `preact/jsx-runtime` and the one next to it
 * still compiles to React's.
 *
 * Note that nothing here bridges reactivity. The renderer re-renders into the same container and
 * Preact diffs, so `ticks` survives a prop change — which is exactly what the other three
 * renderers needed a reactive bag, a compiled companion module and a store to achieve.
 */

declare global {
  interface Window {
    __preactIsland?: { mounted: number; destroyed: number };
  }
}

const tally = () => (window.__preactIsland ??= { mounted: 0, destroyed: 0 });

export const PreactTicker = deckPreact(
  ({ label = "a preact island", step = 0 }: { label?: string; step?: number }) => {
    const [ticks, setTicks] = useState(0);

    useEffect(() => {
      tally().mounted++;
      const timer = setInterval(() => setTicks((n) => n + 1), 100);
      return () => {
        tally().destroyed++;
        clearInterval(timer);
      };
    }, []);

    return (
      <div class="ticker is-preact" data-preact-ticks={ticks} data-preact-step={step}>
        <span class="ticker-label">{label}</span>
        <strong class="ticker-count">{(ticks / 10).toFixed(1)}s</strong>
        <em class="ticker-step">deck click {step}</em>
      </div>
    );
  },
);

// examples/showcase/src/solid-ticker.solid.tsx
/** @jsxImportSource solid-js */
import { createSignal, onCleanup, onMount } from "solid-js";

import { deckSolid } from "@kadal/deck-solid";

/**
 * A Solid component on a slide, for the islands tour.
 *
 * `.solid.tsx`, because React's plugin and Solid's both want `.tsx` and their transforms are
 * mutually unintelligible; the deck's vite.config hands this glob to both so each leaves the
 * other's files alone. The collision is at the type level too — the deck's tsconfig points JSX at
 * React — so the file opens with a `@jsxImportSource` pragma, which is the per-file version of the
 * same statement. Both are needed; neither implies the other.
 *
 * Note what the body does NOT do: it runs once. `step` is read inside the JSX, so only that one
 * expression re-runs when the deck hands over new props — which is the whole of Solid, and the
 * reason the renderer passes a store rather than an object.
 */

declare global {
  interface Window {
    __solidIsland?: { mounted: number; destroyed: number };
  }
}

const tally = () => (window.__solidIsland ??= { mounted: 0, destroyed: 0 });

export const SolidTicker = deckSolid((props: { label?: string; step?: number }) => {
  const [ticks, setTicks] = createSignal(0);

  onMount(() => {
    tally().mounted++;
  });

  const timer = setInterval(() => setTicks((n) => n + 1), 100);
  onCleanup(() => {
    tally().destroyed++;
    clearInterval(timer);
  });

  return (
    <div class="ticker is-solid" data-solid-ticks={ticks()} data-solid-step={props.step ?? 0}>
      <span class="ticker-label">{props.label ?? "a solid island"}</span>
      <strong class="ticker-count">{(ticks() / 10).toFixed(1)}s</strong>
      <em class="ticker-step">deck click {props.step ?? 0}</em>
    </div>
  );
});
